feature/UCA-687-Add-filtered-contractlist
UnicacityAddon/unicacityaddon-addon pull request #688
Opened 2023-06-30 15:25 UTC by Gelegenheitscode

closes #687

2023-06-30 18:14 UTC, rettichlp requested changes
Siehe Kommentare

2023-06-30 18:14 UTC, rettichlp commented on core/src/main/java/com/rettichlp/unicacityaddon/listener/faction/ContractListener.java
> +            if(this.unicacityAddon.configuration().message().filteredContractlist().get()) {
Bitte die datei formatieren (STRG+ALT+L)

2023-06-30 18:17 UTC, Dimiikou commented
Katastrophal

2023-06-30 18:19 UTC, Dimiikou requested changes

2023-06-30 18:19 UTC, Dimiikou commented on core/src/main/java/com/rettichlp/unicacityaddon/listener/faction/ContractListener.java
> +                if(coloredmsg.contains(ColorCode.RED.getCode())) {
Geht auch ohne {, würde mir besser gefallen.
Auch fehlt ein ' ' zwischen if und der Klammer...

2023-07-03 12:47 UTC, rettichlp commented
#700

2023-07-03 12:47 UTC, closed without merging